import Image from "next/image";
import type { NextPage } from "next";
import Head from "next/head";
import { FaDiscord } from "react-icons/fa";
import { FaSquareXTwitter } from "react-icons/fa6";
import { FaArrowRight } from "react-icons/fa";
import Container from "../src/components/container";
import Header from "../src/components/header";
import { useEffect } from "react";
import { getFrameMetadata } from "frog/next";
import type { Metadata } from "next";
import AnimatedBackground from "../src/components/animated-background";
import GridGallery from "../src/components/grid-gallery";
import FeaturesGrid from "../src/components/features-grid";
export async function generateMetadata(): Promise<Metadata> {
  const frameTags = await getFrameMetadata(
    `${process.env.VERCEL_URL || "http://localhost:3000"}/api`
  );
  return {
    other: frameTags,
  };
}

const Home: NextPage = () => {
  useEffect(() => {
    const container = document.querySelector(".animated-background");
    const numberOfTiles = 20; // Adjust based on the container size and tile size

    for (let i = 0; i < numberOfTiles; i++) {
      const tile = document.createElement("div");
      tile.className = "tile";
      // Randomize the animation delay for each tile for a more dynamic effect
      tile.style.animationDelay = `${Math.random() * 5}s`;
      if (container) {
        container.appendChild(tile);
      }
    }
  }, []);

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Header />

      <section className="bg-white py-[64px] relative" id="hero-banner">
        <div className="container lg:container mx-auto relative z-[2]">
          <div className="flex flex-col items-start px-5 text-lg leading-6 max-w-[760px]">
            <div className="flex gap-px px-5 py-2.5 mb-2 bg-white rounded-3xl border border-solid border-zinc-100 text-neutral-900 max-md:flex-wrap max-md:pr-5 max-md:max-w-full text-left">
              👋 We're hiring self-motivated people to join the team.
            </div>
            <h1 className=" font-semibold text-neutral-900 text-[32px] lg:text-[48px] leading-tight text-left mb-[24px] lg:mb-[32px]">
              A boon from Base God. Let this silent emblem of your courage
              reside within your hat.
            </h1>
            <p className="mt-2.5 text-left  max-md:max-w-full">
              Explore a new era of decentralized possibilities where security
              meets innovation. Ljubljana is your gateway to borderless
              transactions, financial empowerment, and a world without limits.
            </p>
            <form>
              <div
                role="group"
                aria-label="Actions"
                className="flex gap-4 justify-center mt-12  font-medium whitespace-nowrap max-md:mt-10"
              >
                <button className="btn btn-primary">Get your boon</button>
                <button className="btn btn-secondary">
                  <label htmlFor="shop-input">Go To Shop</label>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/85aab849a9ef6606738d89d1fc525bd1455106187391fac2e9eb3a66dfd099af?apiKey=da983b91ec1d46989670bd2839624a11&"
                    className="w-6 aspect-[1.04]"
                  />
                </button>
              </div>
            </form>
          </div>
        </div>

        <div className="animated-background"></div>
        <GridGallery />
      </section>

      <Container>
        <FeaturesGrid />
      </Container>
      <Container className="bg-[#171717]">
        <div className="flex flex-col lg:grid grid-cols-2 lg:flex-nowrap xl:flex-row gap-[32px] lg:gap-[64px] items-center justify-center lg:px-[24px]">
          <figure className="advert-image fluid-gradient fluid-gradient-left">
            <Image
              loading="lazy"
              src="/images/proto_female_costume_teaser.gif"
              className="rounded-[32px]"
              alt="Image description"
              width={760}
              height={400}
            />
          </figure>

          <div className="block flex flex-col gap-[32px] lg:gap-[16px] text-left max-w-[760px]">
            <h3 className="text-2xl lg:text-4xl font-semibold text-white mb-[20px]">
              Empowering Tomorrow's Innovations with Ljubljana
            </h3>

            <p className=" text-white mb-[20px]">
              Step into the world of Ljubljana Blockchain – where
              decentralization, transparency, and efficiency converge to create
              a foundation for groundbreaking applications.
            </p>

            <div className="rounded-[8px] border-[2px] border-slate-200  px-[16px] py-[16px]">
              <b className="text-xl text-white mb-[20px]">
                Immutable Supply Chain Tracking
              </b>
              <p className="font-normal text-white">
                Utilize Ljubljana Blockchain to ensure transparency and
                traceability throughout supply chains, minimizing fraud and
                enhancing accountability.
              </p>
            </div>
          </div>
        </div>
      </Container>

      <Container className="bg-slate-200">
        <div className="flex flex-col lg:grid grid-cols-2 lg:flex-nowrap xl:flex-row gap-[32px] items-center justify-center lg:px-[24px]">
          <div className="block flex flex-col gap-[32px] lg:gap-[16px] text-left max-w-[560px]">
            <h3 className="text-2xl lg:text-4xl font-semibold  mb-[20px]">
              Empowering Tomorrow's Innovations with Ljubljana
            </h3>

            <p className="  mb-[20px]">
              Step into the world of Ljubljana Blockchain – where
              decentralization, transparency, and efficiency converge to create
              a foundation for groundbreaking applications.
            </p>

            <div className="rounded-[8px] border-[2px] border-slate-300  px-[16px] py-[16px]">
              <b className="text-xl mb-[20px]">
                Immutable Supply Chain Tracking
              </b>
              <p className="font-normal ">
                Utilize Ljubljana Blockchain to ensure transparency and
                traceability throughout supply chains, minimizing fraud and
                enhancing accountability.
              </p>
            </div>
          </div>

          <figure className="advert-image fluid-gradient fluid-gradient-left alt">
            <Image
              loading="lazy"
              src="/images/gaias_concept_01.jpg"
              alt="Image description"
              width={760}
              height={400}
            />
          </figure>
        </div>
      </Container>

      <section id={"promotion-banner-main"}>
        <img src="/images/frame-7.gif" loading="lazy" />
      </section>
      <Container id={"promotion-banner"}>
        <AnimatedBackground />
        <div className="promotion-block lg:max-w-[800px] gap-[32px]">
          <h2 className="text-5xl text-white font-semibold">
            This is a Ongaias Promotion
          </h2>
          <p className="text-white">
            A boon of base god. Experience the speed of thought with
            lightning-fast transactions, freeing you from the constraints of
            traditional intermediaries.
          </p>
        </div>
      </Container>

      <Container>
        <h2 className="w-full text-3xl lg:text-5xl font-semibold text-neutral-900  mb-[32px] lg:mb-[64px]">
          Discover Onchain Gaias's Unique Advantages
        </h2>
        <div className="mt-7 w-full max-md:max-w-full">
          <div className="flex gap-[32px] md:flex-nowrap flex-wrap">
            <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow items-start">
                <img
                  src="/images/icons/transactions-1.svg"
                  alt="Transaction Icon"
                  className="max-w-[64px] mb-[16px]"
                />
                <h4 className="text-left text-2xl font-semibold leading-8 text-neutral-900 mb-[16px]">
                  Instant Transactions
                </h4>
                <p className="text-left">
                  Experience the speed of thought with lightning-fast
                  transactions, freeing you from the constraints of traditional
                  intermediaries.
                </p>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow">
                <img
                  src="/images/icons/transactions-2.svg"
                  alt="Transaction Icon"
                  className="max-w-[64px] mb-[16px]"
                />
                <h4 className="text-left text-2xl font-semibold leading-8 text-neutral-900 mb-[16px]">
                  Instant Transactions
                </h4>
                <p className="text-left">
                  Experience the speed of thought with lightning-fast
                  transactions, freeing you from the constraints of traditional
                  intermediaries.
                </p>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow">
                <img
                  src="/images/icons/transactions-3.svg"
                  alt="Transaction Icon"
                  className="max-w-[64px] mb-[16px]"
                />
                <h4 className="text-left text-2xl font-semibold leading-8 text-neutral-900 mb-[16px]">
                  Instant Transactions
                </h4>
                <p className="text-left">
                  Experience the speed of thought with lightning-fast
                  transactions, freeing you from the constraints of traditional
                  intermediaries.
                </p>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow pb-5">
                <img
                  src="/images/icons/transactions-4.svg"
                  alt="Transaction Icon"
                  className="max-w-[64px] mb-[16px]"
                />
                <h4 className="text-left text-2xl font-semibold leading-8 text-neutral-900 mb-[16px]">
                  Instant Transactions
                </h4>
                <p className="text-left">
                  Experience the speed of thought with lightning-fast
                  transactions, freeing you from the constraints of traditional
                  intermediaries.
                </p>
              </div>
            </div>
          </div>
        </div>
      </Container>

      <section className="py-[64px] bg-slate-100">
        <div className="lg:container mx-auto px-[16px] lg:px-0">
          <div className="flex flex-col justify-center items-start px-20 py-[136px]  leading-6 bg-blue-500 rounded-[44px] max-md:px-5 cta-container">
            <div className="max-w-[660px] flex flex-col gap-[24px]">
              <h3 className="text-5xl font-semibold leading-[62.4px] text-left text-white">
                {" "}
                Seize Your Future with Ljubljana{" "}
              </h3>
              <p className="text-neutral-900 text-left text-white">
                {" "}
                Empower yourself today for a brighter tomorrow. Embrace
                Ljubljana's decentralized universe – where innovation meets
                security, and possibilities are endless.
              </p>
              <button className="text-center bg-[#fff] rounded-[32px] p-[12px] text-black block max-w-[200px]">
                Free download
              </button>
            </div>
          </div>
        </div>
      </section>

      <footer className="mt-[64px]">
        <div className="w-full py-[32px]">
          <div className="px-[16px] lg:px-[24px] flex lg:flex-nowrap flex-wrap">
            <div className="flex flex-col w-full max-w-[400px] mb-[32px] lg:mb-0">
              <div className="flex flex-col">
                <h3 className="text-left text-4xl font-semibold mb-[24px]">
                  Empowering Dreams, One Dollar at a Time
                </h3>
                <div className="flex gap-3 self-start  mb-[24px] text-2xl leading-7 whitespace-nowrap text-neutral-900">
                  <span className="bg-blue-500 rounded-[32px] p-[12px]">
                    <FaArrowRight size={24} className="text-white" />
                  </span>
                  <a
                    href="mailto:hello@wedoflow.com"
                    className="grow my-auto"
                    aria-label="Email"
                  >
                    hello@wedoflow.com
                  </a>
                </div>

                <div className="flex gap-[12px]">
                  <FaSquareXTwitter size={32} />

                  <FaDiscord size={32} />
                </div>
              </div>
            </div>
            <div className=" grid grid-cols-2 gap-[24px] lg:flex justify-between w-full max-w-[660px] ml-auto lg:flex-nowrap flex-wrap flex-col lg:flex-row">
              <div className=" text-left">
                <h4 className="font-semibold text-black uppercase leading-[153%]">
                  Pages
                </h4>
                <div className="mt-7">Demo (Sales)</div>
                <div className="mt-4">Home</div>
                <div className="mt-5">Features</div>
                <div className="mt-5">About</div>
                <div className="mt-5">Insights</div>
                <div className="mt-4">Shop</div>
              </div>
              <div className="text-left">
                <h4 className="font-semibold text-black uppercase leading-[153%]">
                  utilities
                </h4>
                <div className="mt-8">404</div>
                <div className="mt-5">Password</div>
                <div className="mt-5">Checkout</div>
                <div className="mt-5">Blog Details</div>
                <div className="mt-4">Shop Details</div>
              </div>
              <div className=" text-left">
                <h4 className="font-semibold text-black uppercase leading-[153%]">
                  Utility
                </h4>
                <div className="mt-8">Style Guide</div>
                <div className="mt-4">Licencing</div>
                <div className="mt-4">Change Log</div>
                <div className="mt-4">Instructions</div>
              </div>
              <div className="text-left">
                <h4 className="font-semibold text-black uppercase leading-[153%]">
                  Help
                </h4>
                <div className="mt-8">All Templates</div>
                <div className="mt-4">Support</div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex gap-5 justify-between px-[24px] py-[32px] w-full text-lg leading-6 border-t border-solid border-t-slate-300 text-zinc-500 max-md:flex-wrap max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f366d2705bc3bd492734b6363eedb3e6dda85dd6ff4326e46641d8b53b524c92?apiKey=da983b91ec1d46989670bd2839624a11&"
            className="max-w-full aspect-[4] w-[120px]"
            alt=""
          />
          <div className="justify-center self-start py-1 max-md:max-w-full">
            © 2024 - Powered by Webflow with 💙 by Azwedo & Wedoflow
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
